name: finance_app_yandex_smr_2025
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  auto_route: ^10.0.1
  auto_route_generator: ^10.0.1
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  equatable: ^2.0.7
  sensors_plus: ^6.1.1
  fl_chart: ^0.69.1
  
  # Database
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.0.6
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  objectbox_generator: ^4.3.0

flutter:
  assets:
    - assets/icons/
    - assets/images/


  uses-material-design: true
